name: SpigotAdvancedPermissionManager
version: '${version}'
main: com.popopapi.bukkit.BukkitEntryPoint
commands:
  sapm:
    description: The main command
    permission: sapm.command
    usage: /<command> [args...]



